' Realizar un ejercicio ético y profesional de la profesión, desde sus diversos campos de actuación, enfocado en brindar un servicio con calidad y responsabilidad social.
' Responder a las necesidades de la sociedad desde el campo de su profesión.
' Elaborar proyectos de investigación y diseños de programas de intervención en los distintos ámbitos de la ingeniería informática.
' Utilizar metodologías y técnicas propias de la disciplina para estudiar e intervenir objetivamente en diversos campos de la acción humana con el fin de coadyuvar en la consecución del bienestar del individuo, su familia, las organizaciones y la sociedad en general.
' Analizar e investigar fenómenos relacionados con el campo su acción con el objetivo de proponer cambios que favorezcan el bienestar y el desarrollo integral individual y social de las personas y empresas.
' Colaborar en equipos multidisciplinares e interdisciplinares con el fin de realizar un desempeño profesional mucho más efectivo e integral.
' Mostrar iniciativa y espíritu emprendedor para planificar, gestionar, dirigir, impulsar, realizar proyectos orientados a fomentar el desarrollo integral de las personas y empresas.
' Aprender de manera permanente, siendo un profesional en constante actualización.

@startmindmap
title Perfil del egresado

+ Egresado
++ <b>Ejercer</b> ética y profesionalmente
++ <b>Responder</b> necesidades sociales
++ <b>Elaborar</b> proyectos informáticos
++ <b>Utilizar</b> metodologías bienestar
-- <b>Analizar</b> fenómenos sociales
-- <b>Colaborar</b> equipos multidisciplinares
-- <b>Impulsar</b> emprendimiento integral
-- <b>Aprender</b> continuamente